### ISSUE TITLE
请问如何使用Text-Expander 功能？

### ISSUE THREAD

**Issue by qibinying** [dongyuwei/hallelujahIM#105]
具备 Text-Expander 功能 

readme 界面说要读取用户目录下的~/.you_expand_me.json 文件，但我并没有找到这个文件。 

问题如下： 
（1） 请问是否需要手动创建，如果不需要，怎么找到这个文件
（2）如果需要手动穿件，请问在哪个文件夹下创建。

多谢。

**Comment by dongyuwei** [comment]
`~/.you_expand_me.json`在mac/linux系统中指当前登录用户的Home directory 下的一个特殊隐藏文件，内容是标准JSON，如我的是在 `/Users/yuwdong/.you_expand_me.json`, 

```json
{
   "yem":"you expand me",
   "azzd": "爱咋咋地"
}

```

**Comment by dongyuwei** [comment]
第一次需要手动创建这个文件。更新内容后需要重启输入法进程才能生效。如果有报错请检查文件内容是否是合法JSON格式。

**Comment by ylcdwyyx** [comment]
请问怎么重启，我只会杀掉它，不知道怎么启动
