### ISSUE TITLE
西班牙语键盘标点符号问题

### ISSUE THREAD

**Issue by Jiahuan-H** [dongyuwei/hallelujahIM#106]
我的键盘里有西班牙语输入法，从西班牙语输入法切换到哈利路亚的时候，哈利路亚默认的标点符号键盘是西班牙语的，导致符号输入的时候需要想西语符号的位置。比方说问号并不在问号的位置。但是从美国英语输入法切换到哈利路亚之后，符号输入就是美国英语的了。希望哈利路亚的符号输入能一直和英语键盘一致，而不是跟随上一次切换的别的输入法。

**Comment by Jiahuan-H** [comment]
![屏幕快照 2021-04-21 13 40 05](https://user-images.githubusercontent.com/82944585/115547967-32c5e400-a2a7-11eb-98bd-195a03840e1c.png)
![屏幕快照 2021-04-21 13 40 32](https://user-images.githubusercontent.com/82944585/115547995-3d807900-a2a7-11eb-97d1-f3a98b999c38.png)
分别是两个上一个输入源的截图。

**Comment by dongyuwei** [comment]
谢谢反馈，有空了我研究一下。对这种问题不是很懂。

**Comment by Jiahuan-H** [comment]
> 谢谢反馈，有空了我研究一下。对这种问题不是很懂。

期待更新！用起来已经很舒服了！

**Comment by dongyuwei** [comment]
https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L274 

```
[sender overrideKeyboardWithKeyboardNamed:@"com.apple.keylayout.US"];
```

这个应该就是解决这种问题的。有时间我再测试一下，最近用的都是客户的mac。

**Comment by Jiahuan-H** [comment]
> https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L274
> 
> ```
> [sender overrideKeyboardWithKeyboardNamed:@"com.apple.keylayout.US"];
> ```
> 
> 这个应该就是解决这种问题的。有时间我再测试一下，最近用的都是客户的mac。

**Comment by Jiahuan-H** [comment]
> > https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L274
> > ```
> > [sender overrideKeyboardWithKeyboardNamed:@"com.apple.keylayout.US"];
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个应该就是解决这种问题的。有时间我再测试一下，最近用的都是客户的mac。



> https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L274
> 
> ```
> [sender overrideKeyboardWithKeyboardNamed:@"com.apple.keylayout.US"];
> ```
> 
> 这个应该就是解决这种问题的。有时间我再测试一下，最近用的都是客户的mac。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.5.8 使用这个新版试试吧

**Comment by Jiahuan-H** [comment]
> https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.5.8 使用这个新版试试吧
完美解决
