### ISSUE TITLE
按住shift键不能大写

### ISSUE THREAD

**Issue by houyu611** [dongyuwei/hallelujahIM#11]
不知道是不是设置问题，按住shift键不能打出大写的字母

**Comment by dongyuwei** [comment]
10.12系统新问题，周末我看一下。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.6 解决了这个问题。

### to update/reinstall it:
1. delete the hallelujah from `Input Sources`
2. kill the old hallelujah Process
3. replace the hallelujah app in `/Library/Input Methods/`
4. add the hallelujah to `Input Sources`
5. switch to hallelujah, use it.
