### ISSUE TITLE
openSUSE 如何安装 哈利路亚 英文输入法

### ISSUE THREAD

**Issue by Pantyhose-X** [dongyuwei/hallelujahIM#111]
[openSUSE](https://www.opensuse.org/)

开源TTS
[Mozilla's Text-to-Speech](https://github.com/mozilla/TTS)  
[coqui-ai TTS](https://github.com/coqui-ai/TTS) 
[Google Text-to-Speech apk](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en_US&gl=US)

**Comment by dongyuwei** [comment]
哈利路亚 英文输入法 目前只支持Mac。
