### ISSUE TITLE
Mac M1 build please 

### ISSUE THREAD

**Issue by KillingJacky** [dongyuwei/hallelujahIM#112]
Could you please compile the version for Apple M1 silicon?

**Comment by dongyuwei** [comment]
Unfortunately I don't have any M1 machine right now.

**Comment by shenlebantongying** [comment]
I built successfully on the M1 mac (with tons of warning from Xcode), and it works on Apple Silicon mode!

The libmarisa is built from their master branch.

You can download & test my build here: https://github.com/shenlebantongying/hallelujahIM/releases/tag/v1.5.9

<img width="762" alt="image" src="https://user-images.githubusercontent.com/20123683/135358813-075e115f-b367-4b4b-bf5a-b49470780d7e.png">

**Comment by dongyuwei** [comment]
Please try latest version.
see https://github.com/dongyuwei/hallelujahIM/pull/123

**Comment by luckykong** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/7273053/164012808-a6886cb3-7b52-44cf-af28-a195c4dfaad1.png">

It looks like the hallelujah process is still an "Intel" process.

Under 

- Monterey 12.3.1
- MacBook Pro
- Apple M1 Pro

**Comment by dickwu** [comment]
Is there any way to build an M1 version by ourselves?

**Comment by dongyuwei** [comment]
> Is there any way to build an M1 version by ourselves?

I don't know. 

这个输入法没有在M1上开发测试过，我还没有M1芯片的Mac用来测试。

**Comment by dongyuwei** [comment]
please try https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.6.2

**Comment by GOWxx** [comment]
> please try https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.6.2

经过实测在 1.6.2 下，安装后重启电脑，就可以在输入法设置里添加 hallelujah 输入法了，即可正常使用。

After actual testing, it was found that in version 1.6.2, after installing and restarting the computer, you can add the Hallelujah input method in the input method settings and use it normally.

Apple M1 Pro
macOs Ventura 13.5.2
