### ISSUE TITLE
最新的MACOS monterey 系统用不了这个输入法了 大佬怎么办

### ISSUE THREAD

**Issue by leoyangdiary** [dongyuwei/hallelujahIM#114]

**Comment by kinghust007** [comment]
> 等我升级系统了看看

您好，我也是升级了后不能用了，直接安装到一半卡死不动了

**Comment by stevenzeroone** [comment]
> 等我升级系统了看看

你好，作者，同样升级Monterey 安装完全无反应。希望能解决，感谢你

**Comment by dongyuwei** [comment]
我升级了最新的Monterey系统，发现之前安装的hallelujah  输入法确实在输入法切换时没有了。但是可以去Input Sources中手动添加一下hallelujah（注意语言是English中），还能正常使用。

如下：
![image](https://user-images.githubusercontent.com/112451/139585795-9decb99d-8d1b-4ec1-959d-fbc946085cc9.png)

后面有时间再看看，是不是安装脚本需要更新适配一下monterey系统。

**Comment by kinghust007** [comment]
> 我升级了最新的Monterey系统，发现之前安装的hallelujah 输入法确实在输入法切换时没有了。但是可以去Input Sources中手动添加一下hallelujah（注意语言是English中），还能正常使用。
> 
> 如下： ![image](https://user-images.githubusercontent.com/112451/139585795-9decb99d-8d1b-4ec1-959d-fbc946085cc9.png)
> 
> 后面有时间再看看，是不是安装脚本需要更新适配一下monterey系统。

我刚试了下，确实是这样，但是大佬，我问下，为啥我升级系统之后就不能安装了呢？安装到一半就不动了，是因为我之前系统里有这个软件吗？

**Comment by dongyuwei** [comment]
> > 我升级了最新的Monterey系统，发现之前安装的hallelujah 输入法确实在输入法切换时没有了。但是可以去Input Sources中手动添加一下hallelujah（注意语言是English中），还能正常使用。
> > 如下： ![image](https://user-images.githubusercontent.com/112451/139585795-9decb99d-8d1b-4ec1-959d-fbc946085cc9.png)
> > 后面有时间再看看，是不是安装脚本需要更新适配一下monterey系统。
> 
> 我刚试了下，确实是这样，但是大佬，我问下，为啥我升级系统之后就不能安装了呢？安装到一半就不动了，是因为我之前系统里有这个软件吗？

不知道，这种场景之前也没有充分测试。

**Comment by stevenzeroone** [comment]
> 我升级了最新的Monterey系统，发现之前安装的hallelujah 输入法确实在输入法切换时没有了。但是可以去Input Sources中手动添加一下hallelujah（注意语言是English中），还能正常使用。
> 
> 如下： ![image](https://user-images.githubusercontent.com/112451/139585795-9decb99d-8d1b-4ec1-959d-fbc946085cc9.png)
> 
> 后面有时间再看看，是不是安装脚本需要更新适配一下monterey系统。

Monterey 可以使用了。多谢作者

**Comment by stevenzeroone** [comment]
> > > 我升级了最新的Monterey系统，发现之前安装的hallelujah 输入法确实在输入法切换时没有了。但是可以去Input Sources中手动添加一下hallelujah（注意语言是English中），还能正常使用。
> > > 如下： ![image](https://user-images.githubusercontent.com/112451/139585795-9decb99d-8d1b-4ec1-959d-fbc946085cc9.png)
> > > 后面有时间再看看，是不是安装脚本需要更新适配一下monterey系统。
> > 
> > 
> > 我刚试了下，确实是这样，但是大佬，我问下，为啥我升级系统之后就不能安装了呢？安装到一半就不动了，是因为我之前系统里有这个软件吗？
> 
> 不知道，这种场景之前也没有充分测试。

<img width="365" alt="Screen Shot 2021-11-03 at 12 01 20 PM" src="https://user-images.githubusercontent.com/93362643/140008395-01fe5942-2544-4942-b624-3e0abf17da26.png">并且在偏好设置中设置显示翻译也没有用
你好作者，用了一段子之后 hallelujah输入法的翻译无法显示and

**Comment by dongyuwei** [comment]
重启一下hallelujah 输入法进程。在活动管理器中kill掉这个进程操作系统在下次切换到输入法时会自动重启输入法。

**Comment by adonis-lsh** [comment]
> 

我试了,的确,其他的都可以,就微信不行,删除输入法在添加也不行,垃圾微信

**Comment by dongyuwei** [comment]
我的微信可以。重启微信或者重启输入法试试。

**Comment by felixshing** [comment]
今天终于把在M1 Mac上成功用上哈利路亚了，分享一下经验。

1. 我这边直接安装pkg的话，在input source里面根本找不到输入法（它会显示有，但是其实用不了），添加也找不到。解决方案是进去Library/Input Methods里面手动双击哈利路亚安装文件，手动开启进程
2. 然后就可以在input source里面点击添加按钮手动添加输入法了，不过奇怪的是，我这边显示哈利路亚是在Chinese，Simplified下，而不是 @dongyuwei 说的English，推测可能与系统语言有关？我的系统语言是English。Anyway，在添加的时候可以在左下角搜索输入法，可以直接搜到

<img width="911" alt="image" src="https://user-images.githubusercontent.com/61814345/182604930-cfcbd29a-00ca-4538-9901-275e52563054.png">


<img width="680" alt="image" src="https://user-images.githubusercontent.com/61814345/182604884-a09dae9f-47a0-4fdf-96e5-586059cb46de.png">

**Comment by dongyuwei** [comment]
> 显示哈利路亚是在Chinese，Simplified下，而不是 @dongyuwei 说的English

忘了是解决什么问题改成中文的了，`zh-Hans`.
