### ISSUE TITLE
🙏问题：最新的Macos monterey   用不了hallelujah输入法

### ISSUE THREAD

**Issue by stevenzeroone** [dongyuwei/hallelujahIM#115]
前几天更新系统发现切换不了，重启电脑和安装最新版本哈利路亚输入法也还是用不了 ，希望解决问题谢谢🙏

**Comment by dongyuwei** [comment]
先参考这个看一下：https://github.com/dongyuwei/hallelujahIM/issues/114#issuecomment-955701662

**Comment by stevenzeroone** [comment]
> 先参考这个看一下：[#114 (comment)](https://github.com/dongyuwei/hallelujahIM/issues/114#issuecomment-955701662)

> 
<img width="844" alt="Screen Shot 2021-11-01 at 9 47 10 AM" src="https://user-images.githubusercontent.com/93362643/139610505-e8b1ea55-fcb4-4d25-a779-adb3c7c034fb.png">

可以了。多谢作者

**Comment by stevenzeroone** [comment]
> 先参考这个看一下：[#114 (comment)](https://github.com/dongyuwei/hallelujahIM/issues/114#issuecomment-955701662)

很奇怪之前安装重启都没用，现在竟然就可以了。

**Comment by dongyuwei** [comment]
我把这个issue先关闭了，保留114那个讨论比较多的issue。
