### ISSUE TITLE
请问如何构建.bin词库

### ISSUE THREAD

**Issue by tigercong** [dongyuwei/hallelujahIM#116]
请问如何构建.bin词库

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/blob/master/dictionary/build-binary-trie.sh

**Comment by dongyuwei** [comment]
另外参考这段文档: https://github.com/dongyuwei/hallelujahIM#%E6%9E%84%E5%BB%BA-libmarisaa

**Comment by tigercong** [comment]
谢谢大佬的解答：
