### ISSUE TITLE
最新的Mac OS monterey 切到微信里面输入法就不管用了

### ISSUE THREAD

**Issue by jasonzgk** [dongyuwei/hallelujahIM#117]
只有系统的键盘 中文和英文。选不了hallelujah

电脑是m1 max

**Comment by dongyuwei** [comment]
重启大法试一下: 微信，输入法，系统。。。

**Comment by JerMouse** [comment]
问题解决了吗，我也是monterey，装了不知道在哪里启动

**Comment by dongyuwei** [comment]
参考 
https://github.com/dongyuwei/hallelujahIM/issues/114
