### ISSUE TITLE
一名小白关于“中/英文切换”和“双拼“的小小建议

### ISSUE THREAD

**Issue by ditelvhui** [dongyuwei/hallelujahIM#118]
⭐️独一档的英文翻译app，还是免费开源软件，为作者大大点一个大赞！但在实际使用中有一些可以改进的点：
1.中/英文切换键失效：在使用该输入法时，想要切换成中文，按“中/英“键不能换成系统中文输入法而是切换英文大小写，并且系统原生长按shift键就可以键入大写英文。希望作者大大能修复，或者**关闭按“中/英”键切换大小写**。
2.列表中的中文只支持全拼，希望能**支持双拼**。
（因为鄙人是个程序小白，不会敲代码，只能寄希望于大佬了！）

⭐️最后祝您生活愉快，工作顺利，家庭和睦！

**Comment by ditelvhui** [comment]
作者大大，我通过改键解决了！我把中/英文键映射成ctrl+space了，然后我现在可以直接按中/英文键切换中英文了。软件是Karabiner-Elements，然后从https://ke-complex-modifications.pqrs.org/#caps_lock_toggle_chinese_english上面导入规则就ok了

**Comment by dongyuwei** [comment]
最新版改成键盘右侧shift键来关闭/开启候选词提示。
https://github.com/dongyuwei/hallelujahIM/issues/102
