### ISSUE TITLE
标点符号选词的问题

### ISSUE THREAD

**Issue by huj156** [dongyuwei/hallelujahIM#12]
目前的输入法已经非常好用了, 不过如果再能解决标点符号选词的问题的话, 对于我来说就完美了. 标点符号选词主要是打出单词后必须先按空格或者回车然后再打标点, 否则单词消失.  我的系统是Sierra 10.12.4.

**Comment by dongyuwei** [comment]
谢谢反馈，抽空看看。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.7 解决了这个问题，
## update/reinstall
1. delete the hallelujah from Input Sources
2. kill the old hallelujah Process
3. replace the hallelujah app in /Library/Input Methods/.
4. add the hallelujah to Input Sources
5. switch to hallelujah, use it.
