### ISSUE TITLE
issue 里修改info.plist 实现 CAPS 键切换中英文无效

### ISSUE THREAD

**Issue by Attiv** [dongyuwei/hallelujahIM#122]
希望可以实现 大小写键 切换中英文

**Comment by throne-developer** [comment]
关于这个问题，我觉得需要用 hallelujahIM 作为英文输入法时，一般是集中时间需要大量输入英文的时候才用，一般情况下并不会用这个输入法，比如日常聊天之类的用自带的ABC够用了。
从这个角度考虑，并不需要频繁的切换 hallelujahIM 和 中文输入法，所以用 control+space 来切换 hallelujahIM 还可以接受。

**Comment by Attiv** [comment]
> 

我平常还挺用的着的，加上自动切换数入法
