### ISSUE TITLE
M1 pro芯片系统Monterey无法使用毫无反应。

### ISSUE THREAD

**Issue by 86kimi68** [dongyuwei/hallelujahIM#124]
最新款的M1pro 无法使用，安装好后发现不能切换过去 及时切换过去了也是默认英语输入没有任何联想。大神能修复一下这个问题吗。谢啦

**Comment by 86kimi68** [comment]
哦 重启了一下确实可以用了。 看来重启是可以解决大部分问题。

**Comment by dongyuwei** [comment]
M1还没有做特别适配，我现在都没有m1芯片的电脑。
