### ISSUE TITLE
不能出个windows版本吗/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by thomasTAT** [dongyuwei/hallelujahIM#127]

**Comment by dongyuwei** [comment]
能，谁出钱赞助一下开发就可以。

开源产品也是需要时间和精力投入的，windows平台开发我不熟悉。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/PIME/tree/master/python/input_methods/hallelujah 本输入法已经移植到Windows平台。
