### ISSUE TITLE
请问如何完全卸载再重装？

### ISSUE THREAD

**Issue by felixshing** [dongyuwei/hallelujahIM#128]
之前不小心把输入法remove掉了，结果再也装不回去了。每次重装在如下图点击OK后，输入法仍然无法被找到。手动添加输入法也找不到。不知道是哪里冲突了，重启也没用。所以我就想着完全卸载后再重装，请问如何完全卸载了？我使用的是M1 Pro。

<img width="673" alt="image" src="https://user-images.githubusercontent.com/61814345/182029407-7e3c673e-2a75-422c-915c-94b6b0f967da.png">

**Comment by dongyuwei** [comment]
1. 在活动管理器中搜索并且杀死hallelujah输入法进程
2. 输入法是安装到 `/Library/Input Methods/` 这个目录下的。找到文件并且删除
3. 重新下载最新版输入法、安装。
