### ISSUE TITLE
FR: Add a toggle to hide numbers and scrollbar

### ISSUE THREAD

**Issue by StevenLi-DS** [dongyuwei/hallelujahIM#129]
Hi buddy. Thanks a lot for this input method, and it really has saved me tons of time. 

Could you pls consider adding a toggle for the numbers and the scrollbar?
I believe it could make the UI more concise. 

![CleanShot 2022-08-23 at 18 10 08](https://user-images.githubusercontent.com/33796896/186275530-7c2d4d6a-7fe2-4850-bcd3-eb3fc63c4075.png)

An example could be how IntelliSense works in VS code
![CleanShot 2022-08-23 at 18 10 48](https://user-images.githubusercontent.com/33796896/186275527-b34ce9eb-45f2-4c0b-a4c6-cce0c2490632.png)

**Comment by StevenLi-DS** [comment]
Maybe an option to limit the number of results showing so that the scrollbar won't show up?

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/blob/master/src/ConversionEngine.mm#L200
You can modify && build a version for your personal needs.
