### ISSUE TITLE
翻译貌似不见了  能不能配置成Google的翻译

### ISSUE THREAD

**Issue by bang88** [dongyuwei/hallelujahIM#13]

**Comment by bang88** [comment]
kill process 又好了。:cry:

**Comment by dongyuwei** [comment]
配置成Google的翻译，也是可以做的。只不过要联网要翻墙，不是很方便。

**Comment by bang88** [comment]
你有空能不能加一个配置项。默认百度

**Comment by dongyuwei** [comment]
没有兴趣做这个。你可以参考目前的代码来实现（如gs开头的调google suggestion api；以pinyin开头的调用baidu拼音api）

**Comment by bang88** [comment]
ok
