### ISSUE TITLE
能不能提供一个是否默认打开联想功能的开关

### ISSUE THREAD

**Issue by geutopia** [dongyuwei/hallelujahIM#135]
1.  大部分时间不需要联想功能，把它当英文输入法来用
2. 需要的时候用shift打开。

所以期望一个是否默认打开联想功能的开光。

**Comment by dongyuwei** [comment]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/112451/208007237-cab25fa4-8f12-49c6-b80d-5f3a494b3025.png">
Preferences 里面有开关。但是关了之后shift应该不生效。
