### ISSUE TITLE
如何导入自定义词库呢？

### ISSUE THREAD

**Issue by HF706** [dongyuwei/hallelujahIM#138]
作者您好，我是化学专业的学生，有着不少化学名词需要输入，如何导入词库呢？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by dongyuwei** [comment]
如果不考虑翻译功能及音标功能的话，可以参考文档及这个脚本： https://github.com/dongyuwei/hallelujahIM/blob/master/dictionary/build-binary-trie.sh。
