### ISSUE TITLE
按 esc 撤消输入_不生效

### ISSUE THREAD

**Issue by dzshi96** [dongyuwei/hallelujahIM#139]
https://github.com/lencx/ChatGPT

作者您好，我在使用chatgpt这个客户端软件时，使用哈利路亚输入法 按esc键不能撤消输入。
![Untitled](https://github.com/dongyuwei/hallelujahIM/assets/54979250/dab2c8da-a7c4-4363-9c3e-740a2fbc4d6d)

**Comment by dongyuwei** [comment]
我刚测试了Chrome，vscode，iTerm 都是正常的，esc会取消输入。这个是你使用的APP不支持，输入法本身没有对APP做特殊处理，都是一视同仁。

**Comment by dzshi96** [comment]
谢谢了，我修改代码后，重新打包，现在可以了
