### ISSUE TITLE
希望能加入单词输入自动加入空格功能~

### ISSUE THREAD

**Issue by Sev73n** [dongyuwei/hallelujahIM#14]
在写论文的时候苦于mac没有合适的自动语法输入法，Google到了这个！开心不已！
希望能添加自动单词之间添加空格的选项
这样建议词空格键入后，就能自动和后面的单词空开了，比较好看~

thank you hallelujah!

**Comment by dongyuwei** [comment]
谢谢，以前做过这个功能。准备加上，变成可配置的。

2017年5月12日 下午12:19，"king73lin" <notifications@github.com>写道：

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.7 解决了这个问题，使用空格选词后自动附加一个空格（enter回车选词不附加空格）。
## to update/reinstall
1. delete the hallelujah from Input Sources
2. kill the old hallelujah Process
3. replace the hallelujah app in /Library/Input Methods/.
4. add the hallelujah to Input Sources
5. switch to hallelujah, use it.
