### ISSUE TITLE
i have a question about hallelujalM

### ISSUE THREAD

**Issue by Gagafengyijie** [dongyuwei/hallelujahIM#149]
My computer is the latest version of M2,I also installed it according to the steps,But there is no way to switch the input method,How should this be solved。

**Comment by dongyuwei** [comment]
Can ref to https://github.com/dongyuwei/hallelujahIM/issues/114 and https://github.com/dongyuwei/hallelujahIM/issues/133.

- Try re-login your system
- Or remove the input method and add it again manually in Input Source.

**Comment by dongyuwei** [comment]
I can use it on M3 Max, so I believe M2 should be okay. If not, can contact me via wechat.
