### ISSUE TITLE
希望能优化英文上标的连续输入

### ISSUE THREAD

**Issue by Sev73n** [dongyuwei/hallelujahIM#15]
输入类似I don't 这样的语句时，点击’号键无法自动输入上标，会发生字符替换错误。
希望有可能优化！
10.12.4
Thank you hallelujah!

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.7 解决了这个问题。
## update/reinstall
1. delete the hallelujah from Input Sources
2. kill the old hallelujah Process
3. replace the hallelujah app in /Library/Input Methods/.
4. add the hallelujah to Input Sources
5. switch to hallelujah, use it.
