### ISSUE TITLE
请问一下windos平台安装后没有任何反应是怎么回事呢

### ISSUE THREAD

**Issue by fangjinfeng1997** [dongyuwei/hallelujahIM#150]
安装了windows平台的PIME输入法，但是没法打开输入法，只有一个后台进程

**Comment by fangjinfeng1997** [comment]
![屏幕截图 2024-03-03 015504](https://github.com/dongyuwei/hallelujahIM/assets/25128229/05b3e14b-a62f-4559-807c-90d8caaafcd9)

**Comment by dongyuwei** [comment]
PIME laucher运行正常吗？windows版是基于PIME和Python开发的。
windows系统什么版本？

**Comment by fangjinfeng1997** [comment]
我的windows版本：
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎1/‎18
操作系统内部版本	19045.4046
体验	Windows Feature Experience Pack 1000.19053.1000.0

PIME launcher 看起来已经在后台运行中了，但是我不知道如何切换到哈利路亚输入法

**Comment by sadcoldpig** [comment]
一样的问题

**Comment by dongyuwei** [comment]
我开发测试使用的是windows11.

需要请看一下你们的输入法日志内容：

## Log 日志(windows系统中可以搜索 %AppData% 快速定位到)
C:\Users<user>\AppData\Local\PIME\Log

@fangjinfeng1997 @sadcoldpig

**Comment by dongyuwei** [comment]
确保杀毒软件没有限制pime进程。

**Comment by sadcoldpig** [comment]
```
[2024-03-03 17:50:01.014] [PIMELauncher] [info] Restart all backends
[2024-03-03 17:57:13.550] [PIMELauncher] [info] Restart all backends
[2024-03-04 11:57:55.791] [PIMELauncher] [info] Restart all backends
[2024-03-04 11:58:19.205] [PIMELauncher] [info] Restart all backends
```

**Comment by dongyuwei** [comment]
这log看不出问题所在，没有啥帮助呀！

**Comment by dongyuwei** [comment]
如果方便的话可以微信联系我，看看能不能远程debug一下

**Comment by fangjinfeng1997** [comment]
哈哈哈是这个问题吗

**Comment by dongyuwei** [comment]
看来安装程序还有必要改进一下。

**Comment by dongyuwei** [comment]
最新版默认会自动选中哈利路亚输入法了。
