### ISSUE TITLE
windows 切换到 hallelujah 输入法会卡一下, 才能输入. 效果不是好很好.

### ISSUE THREAD

**Issue by thomasTAT** [dongyuwei/hallelujahIM#154]

**Comment by dongyuwei** [comment]
使用Python多线程异步加载词库可能会好一点，今天手头没有windows电脑。等有空了试试效果。

**Comment by dongyuwei** [comment]
试了一下，多线程只能略微改善。

**Comment by dongyuwei** [comment]
最新版优化了一下，优化后只有第一次激活该输入法时会有几秒卡顿（加载词库等）。
后续再切换输入法不会有任何卡顿。

请安装最新版： https://github.com/dongyuwei/Hallelujah-Windows/releases/tag/v1.0.6

**Comment by dongyuwei** [comment]
我准备迁移到sqlite3，应该可以彻底解决这个卡顿问题。
