### ISSUE TITLE
WIN版输入法在excel中无法输入数字

### ISSUE THREAD

**Issue by lingxuejun** [dongyuwei/hallelujahIM#159]
情况：win11 系统钟，输入法无法输入数字，小键盘和数字键都没有反应
输入法版本：1.3.5
系统：Windows 11 专业版 23H2
复现情况：hallelujah输入法激活状态下，wps和ms excel表格中，无法输入数字，切换到其它输入法可以输入

**Comment by dongyuwei** [comment]
谢谢报告，等有空了我看一下。

**Comment by dongyuwei** [comment]
Bug fixed. See https://github.com/dongyuwei/Hallelujah-Windows/releases/tag/v1.0.7
Please download latest [PIME-1.3.6-setup.exe](https://github.com/dongyuwei/Hallelujah-Windows/releases/download/v1.0.7/PIME-1.3.6-setup.exe)
