### ISSUE TITLE
Win10 在 WPS 文字使用中无法使用键盘上方数字及小键盘数字输入

### ISSUE THREAD

**Issue by JasonHollow** [dongyuwei/hallelujahIM#160]
情况：win10 系统中，WPS 输入法无法输入数字，小键盘和数字键都没有反应.。窗口切换时，不同输入法在直接拼写时会遇到一定程度的乱码，默认输入法不能正确拼写。
输入法版本：1.3.5
系统：Windows 10 家庭中文版
复现情况：hallelujah输入法激活状态下，wps和ms excel表格中，无法输入数字，切换到其它输入法可以输入。测试后发现换用word可以。窗口切换时，不同窗口的输入法在直接拼写时会遇到一定程度的乱码，默认输入法不能正确拼写。需要将输入法进行切换一次以后才能正常使用。

https://github.com/dongyuwei/hallelujahIM/assets/147985578/401d15ef-1d89-455f-9603-e8e006976e33

附件：错误测试.mp4

**Comment by dongyuwei** [comment]
参见 https://github.com/dongyuwei/hallelujahIM/issues/159，目前应该已经修复了数字输入的bug。如果还有问题可以重开这个issue.
