### ISSUE TITLE
无法找到用户目录下的~/.you_expand_me.json 文件

### ISSUE THREAD

**Issue by Mantismiao** [dongyuwei/hallelujahIM#162]
开发者你好，我是Mac用户，想要自定义常用词组，但是没有找到用户目录下的~/.you_expand_me.json 文件。期待你的回复～

**Comment by dongyuwei** [comment]
默认是没有 .you_expand_me.json 这个文件的，需要的话自己创建它。完了重启输入法（kill掉它，系统会自动重启它。）
