### ISSUE TITLE
大佬 macbook air 10.15版本下了最新的pkg打不了字T T 老的又打不开

### ISSUE THREAD

**Issue by qiwang717** [dongyuwei/hallelujahIM#165]
已经添加到输入法了，但是一切换过去就打不了字··· 旧版本的打不开··怎么办呀

**Comment by qiwang717** [comment]
听说评论区有个修复bug前的老版本···但是我找不到T T

**Comment by dongyuwei** [comment]
10.15应该是支持的。你试试从Input source中删除它（但不删除文件），再重新手动添加哈利路亚输入法。一般这样之后就正常可用了。

設定-鍵盤-文字輸入手動添加。再不行就退出Mac系统重新登录试试。
