### ISSUE TITLE
macos 10.13.6 下载后用不了打不出字来

### ISSUE THREAD

**Issue by lizhe1204** [dongyuwei/hallelujahIM#168]
下载后没办法使用，已经多次退出后重新登录

**Comment by kristenwriteshere** [comment]
Same issue

**Comment by dongyuwei** [comment]
这是个通用问题，在input source中手动删除hallelujah再重新添加就行。可以参考类似的issue。
我 macOS 14.7 都可以正常使用。

**Comment by lizhe1204** [comment]
删除后再重新添加无法解决，后来下载了上一个版本的可以用

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月13日 18:45 |
| 收件人 | dongyuwei/hallelujahIM ***@***.***> |
| 抄送人 | lizhe1204 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [dongyuwei/hallelujahIM] macos 10.13.6 下载后用不了打不出字来 (Issue #168) |

这是个通用问题，在input source中手动删除hallelujah再重新添加就行。可以参考类似的issue。
我 macOS 14.7 都可以正常使用。

**Comment by dongyuwei** [comment]
我刚测试了一下，用Xcode 15.4编译了一个最新版，在M3 Max macOs 14.7系统上可以正常使用。
需要做的是手动在Input Source中手动删除hallelujah，再手动添加一下hallelujah输入法，然后切换到hallelujah就可以正常使用了。

安装程序不够完善，我也不清楚问题出在哪里。

**Comment by lizhe1204** [comment]
最新版在哪里可以下载

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月13日 19:01 |
| 收件人 | dongyuwei/hallelujahIM ***@***.***> |
| 抄送人 | lizhe1204 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [dongyuwei/hallelujahIM] macos 10.13.6 下载后用不了打不出字来 (Issue #168) |

我刚测试了一下，用Xcode 15.4编译了一个最新版，在M3 Max macOs 14.7系统上可以正常使用。
需要做的是手动在Input Source中手动删除hallelujah，再手动添加一下hallelujah输入法，然后切换到hallelujah就可以正常使用了。

安装程序不够完善，我也不清楚问题出在哪里。

**Comment by dongyuwei** [comment]
Release 里面最新版和最新代码差异很小。

**Comment by lizhe1204** [comment]
好的 感谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月13日 19:06 |
| 收件人 | dongyuwei/hallelujahIM ***@***.***> |
| 抄送人 | lizhe1204 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [dongyuwei/hallelujahIM] macos 10.13.6 下载后用不了打不出字来 (Issue #168) |

Release 里面最新版和最新代码差异很小。

**Comment by dongyuwei** [comment]
觉得好用请给点个star吧，谢谢。
