### ISSUE TITLE
mac 10.14无法使用

### ISSUE THREAD

**Issue by sssweetpotatoes** [dongyuwei/hallelujahIM#169]
mac 10.14无法使用，退出登陆再安装也没反应，在微信无法打字，在wps就可以，但是没有单词框

**Comment by dongyuwei** [comment]
在 Input source 中手动删除再重新添加。

**Comment by dongyuwei** [comment]
我mac 14.7可以正常使用。

**Comment by dongyuwei** [comment]
oh，10.14 系统确实很老了，6年前的系统了。
