### ISSUE TITLE
在全屏状态或者分屏状态下 辅助翻译窗口消失

### ISSUE THREAD

**Issue by Sev73n** [dongyuwei/hallelujahIM#17]
在word全屏或者和chrome分屏的条件下
推荐词输入没有问题 但是键入词之后的辅助翻译窗口无法出现
退出全屏或者分屏状态才能自动出现
<img width="402" alt="qq20170531-174035 2x" src="https://cloud.githubusercontent.com/assets/16495885/26623331/554eadb6-4628-11e7-9dae-ee3c2aad2fa2.png">
<img width="696" alt="qq20170531-174051 2x" src="https://cloud.githubusercontent.com/assets/16495885/26623332/576723bc-4628-11e7-9b8f-1ef1ba7f5064.png">

**Comment by dongyuwei** [comment]
全屏我了解。分屏是指啥，第二个显示器屏幕吗？

**Comment by Sev73n** [comment]
不是 是macos自带的分屏，长按最大化按钮就会出来

**Comment by dongyuwei** [comment]
cool feature :)

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.1 新版改进了一点，最大程度上保证翻译列表保持在视野范围内，建议升级试试。

**Comment by dongyuwei** [comment]
发现在多个屏幕下还有bug，待修正。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.8 改进了多个显示器下面翻译窗口的显示。
