### ISSUE TITLE
Esc Enter 和 空格键不同键入逻辑的问题

### ISSUE THREAD

**Issue by Sev73n** [dongyuwei/hallelujahIM#18]
一个关于完善体验的建议
在文字输入阶段 空格键 选择推荐词
回车键直接键入忽略备选
Esc键应该是撤销所有键入，用于快速的重新输入，比如换一个单词输入
但是现在的esc效果和回车是一样的 都会保留已经键入的字符
再修改的话需要多吃退格，不太方便
希望能够增加esc键的字符取消功能，也和主流的输入法逻辑一致

哈利路亚！

**Comment by dongyuwei** [comment]
esc的逻辑修改起来比较简单。如果主流输入法都这么处理，那就修改一下。

**Comment by Sev73n** [comment]
我在mac上主力使用的百度输入法
和之前用过的搜狗都是这样的~

其实也是利用esc 区别与空格和回车 提供第三种字符处理方式吧 要不和回车重合了

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.8 按Esc键撤销所有键入。
