### ISSUE TITLE
卸载出现bug

### ISSUE THREAD

**Issue by Sev73n** [dongyuwei/hallelujahIM#20]
更新新版 在input文件夹里先删除旧版app 复制新app进来之后 就变成这样了
<img width="598" alt="qq20170602-001807 2x" src="https://cloud.githubusercontent.com/assets/16495885/26686808/14ca354c-4729-11e7-871c-96fa29cb11ee.png">

**Comment by Sev73n** [comment]
<img width="897" alt="qq20170602-002935 2x" src="https://cloud.githubusercontent.com/assets/16495885/26687418/99b5991c-472a-11e7-839d-b9832c7330b0.png">
按照教程输入法选项里删除了 然后在文件夹里也删除了 发现在系统里还有 好奇怪 再添加就会出现上面的bug

**Comment by Sev73n** [comment]
自己解决了 原来是之前的输入法存在于用户的input文件夹中 删除就好了

**Comment by dongyuwei** [comment]
准备加上自动更新、自动重启功能。
