### ISSUE TITLE
esc取消输入会在word中出现小框框

### ISSUE THREAD

**Issue by Sev73n** [dongyuwei/hallelujahIM#21]
在chrome中没问题 怀疑是取消后的命令在word中被识别成了字符

![untitled](https://cloud.githubusercontent.com/assets/16495885/26688222/08af4e1a-472d-11e7-9f0c-e469c47b9652.gif)

**Comment by dongyuwei** [comment]
老版本是否有这个问题？

**Comment by Sev73n** [comment]
我印象中没有 因为老版esc是直接键入英文

**Comment by dongyuwei** [comment]
特殊app内的问题原则上不做特殊处理
