### ISSUE TITLE
翻译调取错误

### ISSUE THREAD

**Issue by Sev73n** [dongyuwei/hallelujahIM#25]
![image](https://user-images.githubusercontent.com/16495885/30110510-4842fa2c-9345-11e7-8bb1-99c56f26be15.png)
![image](https://user-images.githubusercontent.com/16495885/30110547-67e376cc-9345-11e7-8d8c-f4b853a43e54.png)

**Comment by dongyuwei** [comment]
it works for me:

![image](https://user-images.githubusercontent.com/112451/30114676-1eeaeb5c-934b-11e7-853b-f688afb7a4ec.png)
![image](https://user-images.githubusercontent.com/112451/30114696-291355ba-934b-11e7-8677-974aaedbaf6d.png)

你重启一下进程试试？或者安装最新的版本试试？我自己始终使用最新版本。

**Comment by dongyuwei** [comment]
ping me dongyuwei @wechat

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.2 可以自定义配置是否显示翻译列表了。

**Comment by huj156** [comment]
我也出现了翻译错误, 但是我不知道是不是新系统的问题, 刚刚升级的10.13, 并且安装了最新的V1.2.2.

**Comment by dongyuwei** [comment]
新系统兼容问题，在看。

**Comment by dongyuwei** [comment]
最新版 https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.3 解决了在 macOS High Sierra Version 10.13 系统上翻译列表不刷新的问题。

**Comment by dongyuwei** [comment]
![wechat-him](https://user-images.githubusercontent.com/112451/31084016-e7359f1e-a758-11e7-809a-f2f49128c88f.jpeg)

@huj156 欢迎扫码加入hallelujah输入法用户群。
