### ISSUE TITLE
Input English, output Chinese?

### ISSUE THREAD

**Issue by Anonymoosed** [dongyuwei/hallelujahIM#28]
Input English, output Chinese? Possible? Thank you.

**Comment by dongyuwei** [comment]
hi @Anonymoosed, It's possible. Need high-quality dictionary mapping. 
You can use cedict:

- https://cc-cedict.org/wiki/
- https://github.com/dongyuwei/hallelujahIM/blob/master/dictionary/cedict_1_0_ts_utf-8_mdbg.txt

Another way is to call Google translate api, which support english2chinese conversion. You need always online, the privacy also a problem.
