### ISSUE TITLE
iOS / Low Memory / Core Data?

### ISSUE THREAD

**Issue by cemkozinoglu** [dongyuwei/hallelujahIM#3]
Hey just curios, given low memory in iOS and extensions -- would you recommend using your code? Trying to figure out the best way to built a auto-correct on a custom keyboard extension, where memory is even further limited.

**Comment by dongyuwei** [comment]
hi, cemkozinglu. 
On mac you can use `NSSpellChecker `, and on iOS you can try `UITextChecker`. 

And you may interested at https://github.com/dongyuwei/SymSpell.
