### ISSUE TITLE
Evernote窗口输入法无法使用

### ISSUE THREAD

**Issue by kooqilylb** [dongyuwei/hallelujahIM#30]
如题
感谢改进

会持续关注

**Comment by dongyuwei** [comment]
有空会测试一下，谢谢反馈。

**Comment by dongyuwei** [comment]
mac 10.13.5， evernote Version 7.0.3 (456341 Direct)测试正常工作。

**Comment by dongyuwei** [comment]
evernote  Version 7.2.3 (456885 Direct) 测试也正常。

**Comment by dongyuwei** [comment]
麻烦反馈一下操作系统版本及Evernote版本。

**Comment by kooqilylb** [comment]
好了，新安装完毕，重启一下才可以使用。

**Comment by dongyuwei** [comment]
遇到问题在命令行输入 `pkill -9 hallelujah` 杀掉输入法再重启它，一般可以解决问题。
