### ISSUE TITLE
很好用,提个小建议,可以支持五笔输入么,否则输入汉字时,又要切换成其它输入法

### ISSUE THREAD

**Issue by SunLangzi** [dongyuwei/hallelujahIM#31]
很好用,提个小建议,可以支持五笔输入么,否则输入汉字时,又要切换成其它输入法

**Comment by dongyuwei** [comment]
之前支持拼音（使用baidu 拼音 cloud api）。我不会五笔，所以暂时不考虑支持这个，sorry。
