### ISSUE TITLE
能否自动填充空格？

### ISSUE THREAD

**Issue by jisongkun** [dongyuwei/hallelujahIM#33]
在选取英文单词后自动加入一个空格，在写长句子的时候这样能提高效率不少。现在就是选完想要的单词后还要按空格才能写下个单词。

**Comment by dongyuwei** [comment]
hi @jisongkun 
空格键选词默认附加一个空格，enter回车键选词不加空格。

**Comment by jisongkun** [comment]
感谢回复，我可能没说清楚，如果使用数字选词后能自动添加空格的话就很方便，要不然空格选词只能选择第一个词，这样联想出来的词用数字选的话就没什么效率了。

**Comment by dongyuwei** [comment]
fixed. see  https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.4.3

可以在配置窗口配置，默认自动在单词后面附加空格。
![image](https://user-images.githubusercontent.com/112451/60952067-1bfe0980-a32d-11e9-81c0-5be4b3573f55.png)

**Comment by nico-zck** [comment]
> hi @jisongkun
> 空格键选词默认附加一个空格，enter回车键选词不加空格。

目前回车键还是自动加上了空格呀。是否还需要开一个issue处理一下？

**Comment by dongyuwei** [comment]
@nico-zck 不希望有空格可以改配置

**Comment by nico-zck** [comment]
@dongyuwei 哈哈这个我知道，我需要空格键入，但是另外发现回车目前的行为跟你之前的描述不一致——“空格键选词默认附加一个空格，enter回车键选词不加空格”，所以问了一下。

**Comment by dongyuwei** [comment]
不同时间点回复的，造成了一些混乱哈！

**Comment by wanghaojie1233333** [comment]
> 固定。查看 https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.4.3
> 
> 可以在配置窗口配置，默认自动在单词后面附加空格。 ![image](https://user-images.githubusercontent.com/112451/60952067-1bfe0980-a32d-11e9-81c0-5be4b3573f55.png)
怎么打开配置窗口
