### ISSUE TITLE
反馈一个bug: macOS Mojave 10.14系统使用输入法选择联想的备选单词时，数字键和方向键失效

### ISSUE THREAD

**Issue by qwqwe3** [dongyuwei/hallelujahIM#34]
首先感谢作者开发了这款输入法，对我这种科研狗帮助很大。

升级到10.14后，使用输入法选择联想的备选单词时，数字键和方向键失效，切换到系统自带的没有问题，不知道是我自己电脑的问题还是系统的问题。

**Comment by dongyuwei** [comment]
谢谢反馈bug。
几乎每次系统升级都会有新问题出现，我还没有升级到10.14系统，等近期升级后我排查一下。

**Comment by dongyuwei** [comment]
方向键现在好了，可以切换候选词了。数字键还不行，原因待查。
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.9

**Comment by qwqwe3** [comment]
感谢更新，这就去试试

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.3.0 可以使用数字键1~9来选词了。
