### ISSUE TITLE
方向键选词时跳格

### ISSUE THREAD

**Issue by 1900forever** [dongyuwei/hallelujahIM#35]
使用方向键选词的时候，比如我按一下下键，会从候选词的第一个跳到第三个，第五个，第七个，第九个。偶数项无法被选择。

另外，默认输入后按空格会自动空格，这在需要加标点的时候就显得尤为不方便，能不能设置开关让用户自行开启或关闭这个功能？

**Comment by dongyuwei** [comment]
你是什么版本的macOS？
for 10.9 ~ 10.11 mac user: https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.1
for 10.12 ~ 10.13: https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.8
for macOS Mojave 10.14 https://github.com/dongyuwei/hallelujahIM/releases/latest
我从你描述看，貌似是下载的版本不对。

另外，空格键选词默认加一个空格，enter回车选词不加空格。

**Comment by dongyuwei** [comment]
新发布了一版：https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.3.1
macOS 10.12， 10.13，10.14 使用同一发布版本，代码层面探测系统版本做兼容处理。

谢谢反馈问题！

**Comment by dongyuwei** [comment]
我更新了文档，macOS 10.12，10.13（High Sierra），10.14（Mojave）系统都使用同一版本，即https://github.com/dongyuwei/hallelujahIM/releases/latest。
