### ISSUE TITLE
在系统登录时我发现一个问题

### ISSUE THREAD

**Issue by fsleo** [dongyuwei/hallelujahIM#37]
在登录系统时。输入密码，按回车没有反应。有时按一个shift即可，有时好像也不行。必须切换输入法。才能安回车。望修改一下这个问题。我的系统是10.14

**Comment by dongyuwei** [comment]
谢谢反馈问题，有空我排查一下。

**Comment by dongyuwei** [comment]
测试验证确实有这个问题。如果输入密码后加一个空格，再删除空格，就没有问题。
输入密码最好不要用第三方输入法，可能有安全隐患。
