### ISSUE TITLE
输入框会乱跑，而不是在光标的地方

### ISSUE THREAD

**Issue by NathanZhengNaixian** [dongyuwei/hallelujahIM#38]
如图
![2018-10-31 11 28 30](https://user-images.githubusercontent.com/22364863/47775233-25e05f00-dd00-11e8-833a-c5eaff9db239.png)

**Comment by dongyuwei** [comment]
操作系统版本和浏览器版本是？

**Comment by dongyuwei** [comment]
我没有Chrome 69，测试 Mojava + Chrome 70.0.3538.67 没有问题。
你的除了chrome浏览器外，在其它app内输入正常吗？

**Comment by NathanZhengNaixian** [comment]
好像只有Chrome 有这问题

**Comment by dongyuwei** [comment]
重启chrome或者hallelujah输入法进程再试一下？

**Comment by dongyuwei** [comment]
有稳定可重现的步骤可以再open这个issue。
