### ISSUE TITLE
辅助翻译窗口内容显示不全

### ISSUE THREAD

**Issue by cumtliang** [dongyuwei/hallelujahIM#39]
辅助翻译窗口内的内容显示不全，如果比较长，最后几个字会丢失。
如果可以修改翻译窗口的字体，让字体小一点，或者增加翻译内容的换行功能。
autom
<img width="403" alt="screen shot 2019-03-06 at 10 07 12 pm" src="https://user-images.githubusercontent.com/14148856/53877069-504e7a00-405c-11e9-8601-789e4c6032a2.png">

**Comment by dongyuwei** [comment]
谢谢反馈。我知道这个问题一直都存在，只是对cocoa原生组件还是不熟悉，不知道如何实现。可以考虑使用webview来实现，但不知道是否会有性能问题。

**Comment by dongyuwei** [comment]
可以试试用NSTableView来实现。

**Comment by dongyuwei** [comment]
Use multi-line Wrapping Label(NSTextField) component to display translations. 
Bug Fixed.

**Comment by dongyuwei** [comment]
![image](https://user-images.githubusercontent.com/112451/60648600-d1831580-9e72-11e9-8979-ea31dd927293.png)
