### ISSUE TITLE
UI问题反馈

### ISSUE THREAD

**Issue by futantan** [dongyuwei/hallelujahIM#4]
在进行输入的时候，每一次按键都会造成输入框的闪烁，让视觉上及其不爽。希望能够改进^_^

**Comment by dongyuwei** [comment]
这个问题一直存在，我还没有找到方法去解决它。

**Comment by dongyuwei** [comment]
hi @futantan , 今天发布的https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.1 这个版本，会让翻译列表保持在视图范围内，可以试试。闪烁还是存在的，尤其是开始第一次输入时。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.2.2 可以自定义配置是否显示翻译列表了。上一个版本提示性能后，闪烁问题基本消除。
