### ISSUE TITLE
在 vscode 这款编辑器中点击 shift 键切换后输入会有点问题

### ISSUE THREAD

**Issue by MuYunyun** [dongyuwei/hallelujahIM#40]
![image](https://user-images.githubusercontent.com/19354791/54073139-ade20100-42be-11e9-801d-4e95c0284253.png)

在 vscode 这款编辑器中点击 `shift` 键切换后进行输入字母,字母会被被弹出的弹框遮盖.

**Comment by dongyuwei** [comment]
刚才验证了一下，vs code 1.31.1 确实有问题。测试了其它软件，如sublime，iterm2，chrome等均是正常。

谢谢反馈，有空我看一下。


我又测试了一下其它输入法，mac内置的简体拼音输入法，也有同样的bug，这个应该是vs code新版本的bug。

**Comment by dongyuwei** [comment]
vs code 的特殊问题，不考虑做特殊处理。
