### ISSUE TITLE
macos10.14下，按向下箭头，出来备选单词，无法回车输入。

### ISSUE THREAD

**Issue by luweidut** [dongyuwei/hallelujahIM#43]

**Comment by luweidut** [comment]
无法回车输入。

**Comment by dongyuwei** [comment]
10.14.5测试可以回车提交选中的候选词。具体什么版本，在什么软件内使用的？

**Comment by luweidut** [comment]
用的最新版本.
候选栏出现后是没问题的。我的问题主要是切换到hallelujahIM后，按下向下箭头键
就会出现候选词，但不能回车输入。
看截屏
<img width="502" alt="屏幕快照 2019-06-23 下午8 07 33" src="https://user-images.githubusercontent.com/23102583/59976110-9c650080-95f2-11e9-9d97-4f7cc5c3875d.png">

**Comment by luweidut** [comment]
下图情况没问题。就是当输入完discussion后，直接按向下箭头，就会出现上面截图情况，在那种情况下，回车无效。
<img width="342" alt="屏幕快照 2019-06-23 下午8 09 47" src="https://user-images.githubusercontent.com/23102583/59976130-ddf5ab80-95f2-11e9-9008-250d9c50628e.png">

**Comment by dongyuwei** [comment]
oh，我问的是osx操作系统的具体版本。看截图软件是在chrome浏览器内吧？测试了我这没有问题。

**Comment by luweidut** [comment]
macos是10.14.5.
Safari浏览器

**Comment by dongyuwei** [comment]
我测试了safari，无法重现问题，不清楚我们的操作差异在哪里？

**Comment by luweidut** [comment]
> 我测试了safari，无法重现问题，不清楚我们的操作差异在哪里？

我的操作是：
（1）切换到hallelujahIM输入法
（2）然后输入单词，比如输入discussion
  (3) 然后马上按键盘上“⬇️”按键，又会出现候选词，此时，按回车无效。
如下图
<img width="235" alt="屏幕快照 2019-06-24 下午3 00 30" src="https://user-images.githubusercontent.com/23102583/59997984-e270a180-9690-11e9-8b78-d05a9487d79e.png">
<img width="173" alt="屏幕快照 2019-06-24 下午3 00 44" src="https://user-images.githubusercontent.com/23102583/59997990-e69cbf00-9690-11e9-9b44-0e11c56d8fb1.png">

**Comment by dongyuwei** [comment]
Safari Version 12.1.1 (14607.2.6.1.1) 按你以上描述的步骤操作，当输入 `discussion` 完成之后按下键则选中 `discussions` ，回车提交 `discussions`。无法重现bug。

**Comment by dongyuwei** [comment]
你能试试在chrome浏览器内使用是否正常吗？以及其他软件内使用是否正常。logout/restart系统后有无变化？

**Comment by luweidut** [comment]
office正常,输入完单词后，按键盘向下按键，没有候选词提示。
chrome正常输入完单词后，马上按键盘向下按键，没有像safari一样有候选单词，但有汉语意思提示框。
<img width="381" alt="屏幕快照 2019-06-24 下午3 57 31" src="https://user-images.githubusercontent.com/23102583/60001370-ed2f3480-9698-11e9-94e6-6e45fffe67b2.png">
texpad下正常输入完单词，按键盘向下按键，会出现非utf-8错误，估计在按键盘上向下按键，会出现一些不显示的字符。

**Comment by luweidut** [comment]
只要不按键盘上的向下按键，一切ok。

**Comment by dongyuwei** [comment]
@luweidut 我今天重现了这个问题，在很多app（safari，chrome）内都可以。已经修正。谢谢反馈bug！

下载最新输入法：https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.3.4 重新安装应该就好了。

**Comment by dongyuwei** [comment]
update/reinstall
- delete the hallelujah from Input Sources
- kill the old hallelujah Process (kill it by `pkill -9 hallelujah`, check it been killed via `ps ax|grep hallelujah` )
- replace the hallelujah app in /Library/Input Methods/.
- add the hallelujah to Input Sources
- switch to hallelujah, use it.
