### ISSUE TITLE
提醒MacOS 10.14.5需要重启后才好使

### ISSUE THREAD

**Issue by dalianblue** [dongyuwei/hallelujahIM#45]
安装之后在Word或Pages下均切换不到HallelujahIM，正当我绝望的时候，突然发现在Finder的搜索框和Terminal里面居然可以启动HallelujahIM，使用正常，这是为什么？

**Comment by dongyuwei** [comment]
没有针对特定app的特殊处理。麻烦修改一下标题（更精确的描述）。

**Comment by dongyuwei** [comment]
![image](https://user-images.githubusercontent.com/112451/60568358-34a37800-9d9f-11e9-94c5-c3a9cbd9e075.png)
我的系统也是MacOS 10.14.5，测试Pages.app中使用这个输入法没有问题。你安装输入法后可以重新登录系统或者重启系统再试试。输入法是特殊的app，有些用户反馈不能正常使用，重新登录系统就正常了。

**Comment by dongyuwei** [comment]
没有安装word，无法做测试。

**Comment by dalianblue** [comment]
重启后正常了。刚安装后Preference打不开，Pages，Word，keynote这些app里面启动不了输入法，重启后好使了！感谢！非常棒的app。

**Comment by dongyuwei** [comment]
重启是比较重的操作，一般只需要logout当前用户，再login就行了。
