### ISSUE TITLE
即时翻译功能多试几次就弹不出来了

### ISSUE THREAD

**Issue by of0** [dongyuwei/hallelujahIM#50]
切换输入法再切回来也弹不出翻译框
系统版本：Macos Mojave10.14.6
目前解决办法只有重启电脑...

**Comment by dongyuwei** [comment]
能不能报告一下出问题的具体输入是什么单词？

**Comment by tian6415** [comment]
the   就翻译不出来，翻译就出现过一次   就再也不出来了

**Comment by dongyuwei** [comment]
![image](https://user-images.githubusercontent.com/112451/62908485-e2487480-bdaa-11e9-91be-4238187f2b4e.png)
我在10.14.5系统下测试功能正常。请报告一下操作系统版本，使用的app及版本。

**Comment by liaohui1080** [comment]
这个翻译是自动弹出的吗？ 我这没有出现这个功能

**Comment by dongyuwei** [comment]
安装 https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.4.7 这个版本试试。可能需要重新登录操作系统。@of0 @tian6415 @liaohui1080
