### ISSUE TITLE
输入含有撇号「'」的单词或者短语时总会多打一个空格

### ISSUE THREAD

**Issue by beitanglanwu** [dongyuwei/hallelujahIM#52]
因为我不想在输入单词的时候总敲两个空格，所以我开启了「输入单词自动加入空格」的选项，但这也带来了一个很讨厌的问题：如果输入 there's 之类的词语，按下撇号会自动将单词上屏**并添加一个空格**，变成 there 's。即便手动输入 there 也会**自动添加空格**。
如果关掉「输入单词自动加入空格」的选项，那么我就没有办法像 abc 键盘一样自然地添加空格，必须先敲一下空格来将我敲好的单词上屏，再添加一个空格，这就大大增加了击键量。

说回来，为什么会有这样一个设置呢？难道真的会有连续输入大量英文单词，却又不用输入单词和单词之间的空格的情况吗？

**Comment by dongyuwei** [comment]
是否自动附加空格这个需求真是众口难调，参考之前的 https://github.com/dongyuwei/hallelujahIM/issues/14

不过你描述的问题确实体验不好，有优化的空间。

**Comment by charonfletcher** [comment]
另外，输入 a 和 i 的时候反倒不会自动添加空格，这就使得这个功能很难受，开也不是，不开也不是。
我的想法是：关闭enter和shift还有空格选词，同时关闭自动添加空格，只在通过数字选词时添加空格。
因为在英文输入中，输入空格是一个十分正常的操作，把空格作为一个选词的方法不太合理，有点像是在中文输入法中输入英文时的体验。
如果这样改了的话，在不需要候选的时候可以像abc键盘一样正常输入英文，需要候选的时候用数字键就可以上屏了，还能自动加个空格，岂不美哉

**Comment by dongyuwei** [comment]
或者折中一下，关闭`输入单词自动加入空格`选项后，通过数字选词时还自动添加空格。
空格选词是很多人需要的功能，应该不止一个用户提过这个需求，所以这个功能的删减还是需要谨慎的。

**Comment by charonfletcher** [comment]
明白您的考虑，但其实在现在的版本，输入某个单词后要敲一下空格来完成单词的键入+空格
如果取消了这个选项，在单词键入完成之后不添加空格，用户手动输入空格的话，其实操作量是一样的，只不过用户在敲空格键的时候是自己在添加空格，而不是告诉输入法「我要加一个空格」
当然我的想法可能欠考虑，希望您能把这个功能做好，输入法是相当不错的，但这个空格确实让我很抓狂

**Comment by wli64** [comment]
今天刚刚使用这个输入法，一点想法不知道能否解决这个问题。

能否把键入符号不识别为选择默认字，而是把符号识别为类似普通的字母输入，这样就能实现直接输入 there's 然后空格选中并自动加上空格。同样的如果是输入句号，就是键盘键入 end. 然后空格默认并自动在句号后添加空格。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.5.7
