### ISSUE TITLE
请问 Text Expander 的功能要如何使用？

### ISSUE THREAD

**Issue by charonfletcher** [dongyuwei/hallelujahIM#53]
readme 界面说要读取**用户目录下的`~/.you_expand_me.json` 文件**，但我并没有找到这个文件，手动创建并注销重新登录还是无法读取。

**Comment by dongyuwei** [comment]
这个文件默认是没有的，需要用户自己在自己的home目录下创建。内容是合法的JSON（key：value），如
`{"yem":"you expand me"}` 然后重启输入法进程即可。注销重新登录应该也可以的。

**Comment by dongyuwei** [comment]
如果还不行，在命令行下执行
`cat ~/.you_expand_me.json`
把内容贴上来我看看。

**Comment by charonfletcher** [comment]
回头我看看，现在电脑不在手边

**Comment by charonfletcher** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/38058430/63898595-3d759a80-ca2c-11e9-8780-754f7d604d48.png">

虽然显示出来了但并没有效果。

**Comment by dongyuwei** [comment]
输入 yem没有提示 you expand me？需要重启输入法进程

**Comment by dongyuwei** [comment]
哦，你的json文件内容不合法。
```json
{
"yem":"you expand me",
"ruok": "are you ok?"
}
```
