### ISSUE TITLE
MacOS 10.15 不能通过软件包安装，卡在了“正在运行软件包脚本”

### ISSUE THREAD

**Issue by sheng-chen** [dongyuwei/hallelujahIM#57]
![image](https://user-images.githubusercontent.com/33170624/64559089-c30b1b80-d345-11e9-825b-0e955a3b99f4.png)
如图

**Comment by dongyuwei** [comment]
我的系统是10.14.5
10.15还没有发布正式版吧？等我升级到10.15后测试看看。或者你下载这里到zip包，解压后手动安装，安装步骤是：
1. Copy the app to /Library/Input\ Methods/
2. Go to System Preferences --> Input Sources --> click the + --> select English --> select hallelujah 
3. Switch to hallelujah 
[hallelujah.app.zip](https://github.com/dongyuwei/hallelujahIM/files/3593157/hallelujah.app.zip)

**Comment by bang88** [comment]
真的是这样哈哈。

**Comment by dongyuwei** [comment]
系统升级到10.15.3 (19D76)，使用输入法最新安装包 测试没有问题。

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/73631963-63673100-4695-11ea-9674-605b7e842382.png)

**Comment by dongyuwei** [comment]
@bang88 系统是10.15的具体版本是？
等待一会，不行杀掉安装进程重试一下。

**Comment by bang88** [comment]
跟你一样 最新的。

还有一个问题不好描述，就是有时候会 插入之前输入的字符。 这样在写代码的时候就很烦。

**Comment by dongyuwei** [comment]
这个输入法其实不适合用于编程。更合适的场景是文字聊天、撰写邮件和科研论文等。编程的话编辑器和 IDE 本身有自动补全等功能。

**Comment by seewinds** [comment]
<img width="734" alt="截屏2020-02-28下午2 25 07" src="https://user-images.githubusercontent.com/17062094/75516124-a0290c80-5a36-11ea-9fac-e62faa070a9d.png">

最新的`1.5.0`还是无法正常安装，系统为`10.15.3`。
尝试了杀进程重启，依然如此。

**Comment by dongyuwei** [comment]
我系统升级到 10.15.3 也没法复现问题，你们先试试手动安装吧：
[hallelujah.app.zip](https://github.com/dongyuwei/hallelujahIM/files/4267125/hallelujah.app.zip)
- Unzip the app, copy it to /Library/Input\ Methods/ 
- Go to System Preferences --> Input Sources --> click the + --> select English --> select hallelujah

**Comment by what2003** [comment]
原来本来用的挺好，突发臆想升级新版本，出现楼主一样的问题后，又手动安装zip，输入法是出现了，但进程中没有，目前仍无法使用。

**Comment by bang88** [comment]
> 原来本来用的挺好，突发臆想升级新版本，出现楼主一样的问题后，又手动安装zip，输入法是出现了，但进程中没有，全部删了，重新安装居然成功了，重启电脑后可以使用了。之前不成功是不是有旧版本的原因，过程供参考。

删了再装就可以安装了

**Comment by sheng-chen** [comment]
> 原来本来用的挺好，突发臆想升级新版本，出现楼主一样的问题后，又手动安装zip，输入法是出现了，但进程中没有，全部删了，重新安装居然成功了，重启电脑后可以使用了。之前不成功是不是有旧版本的原因，过程供参考。

感谢，确实是这个原因，在finder中全局搜索hallelujah，然后把相关文件删除，再重新安装就成功了。

**Comment by dongyuwei** [comment]
> > 原来本来用的挺好，突发臆想升级新版本，出现楼主一样的问题后，又手动安装zip，输入法是出现了，但进程中没有，全部删了，重新安装居然成功了，重启电脑后可以使用了。之前不成功是不是有旧版本的原因，过程供参考。
> 
> 感谢，确实是这个原因，在finder中全局搜索hallelujah，然后把相关文件删除，再重新安装就成功了。

输入法一般安装目录只有 2 个地方： `/Library/Input\ Methods/` 和 ` ~/Library/Input\ Methods/`，前者是全局的，后者是当前登录用户的用户主目录下。现在主流的输入法大多安装在全局目录。
