### ISSUE TITLE
由于公司笔记本安全设置我的本机无法访问https://localhost:62718这个端口， 是否有其他方式可以设置输入法？

### ISSUE THREAD

**Issue by zhuliangyu** [dongyuwei/hallelujahIM#59]
由于公司笔记本安全设置我的本机无法访问https://localhost:62718这个端口， 是否有其他方式可以设置输入法， 谢谢？

**Comment by dongyuwei** [comment]
暂时没有其他办法。
谢谢反馈，等不忙了重构一下用户设置这块的功能，使之不依赖 web ui。

**Comment by dongyuwei** [comment]
@zhuliangyu 我今天想到一种办法：可以通过命令行 `defaults` 命令来修改输入法配置。

- 显示输入法所有默认配置项：
``` 
defaults read github.dongyuwei.inputmethod.hallelujahInputMethod
```
输出如下：

```
{
    commitWordWithSpace = 1;
    showTranslation = 1;
}
```
- 配置输入时不显示翻译窗口（1显示，0不显示）：
```
defaults write github.dongyuwei.inputmethod.hallelujahInputMethod showTranslation 0
```

- 配置提交候选词时不自动附加空格（1加空格，0不加空格）：
```
defaults write github.dongyuwei.inputmethod.hallelujahInputMethod commitWordWithSpace 0
```

**Comment by dongyuwei** [comment]
可以下载最新pkg安装文件试试： https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.4.9

**Comment by dongyuwei** [comment]
目前有2种方法可以配置输入法了：通过`defaults`命令行或者web page这2种界面。

**Comment by dongyuwei** [comment]
`defaults`命令行参考链接： https://pawelgrzybek.com/change-macos-user-preferences-via-command-line/

**Comment by zhuliangyu** [comment]
感谢您的工作!! 👍
