### ISSUE TITLE
可以添加自定义词典吗

### ISSUE THREAD

**Issue by Having-Liu** [dongyuwei/hallelujahIM#61]
我是一个律师，有些法律用语需要参考另外一个字典，叫《布莱克法律词典》，希望可以自己导入词典，并且进行词频设置等，期待回复哦

**Comment by Having-Liu** [comment]
谢谢回复！可以让我们自己一个一个设置吗

在 2019年9月12日，下午9:36，dongyuwei <notifications@github.com> 写道：

﻿

目前不能导入。
导入不难做，不好处理的是词频设置，需要与现有词库适配。

**Comment by dongyuwei** [comment]
抱歉现在还不能。自动补全的词库是预先编译的，导入词库需要提供接口才行。

**Comment by dongyuwei** [comment]
你要是能提供词典数据，我可以帮你定制一版，集成自定义词库。我需要先了解一下你这个法律词库的数据结构/格式。

**Comment by Having-Liu** [comment]
感谢感谢，您需要什么文件格式的词库呀～

在 2019年9月18日，下午1:22，dongyuwei <notifications@github.com> 写道：

﻿

你要是能提供词典数据，我可以帮你定制一版，集成自定义词库。我需要先了解一下你这个法律词库的数据结构/格式。

**Comment by dongyuwei** [comment]
纯文本格式的就行。你的辞典有授权吗？不要有法律纠纷。

**Comment by Having-Liu** [comment]
刚刚问了我认识的一个知识产权的律师，自己用，不盈利是没有法律问题的。

您是准备添加到后台辞典、让大家都可以用吗？

在 2019年9月18日，下午2:26，dongyuwei <notifications@github.com> 写道：

﻿

纯文本格式的就行。你的辞典有授权吗？不要有法律纠纷。

**Comment by dongyuwei** [comment]
不是给所有人用，是给你定制一个版本。词库可以发我邮箱，等有空了给你定制一下。
