### ISSUE TITLE
关于CAPSLOCK键的功能切换

### ISSUE THREAD

**Issue by HernandoR** [dongyuwei/hallelujahIM#68]
原生输入法提供使用CAPSLOCK键进行中/英文输入法切换的选项

hallelujah并未提供改选项，导致从系统与安生输入法切换入hallelujah后无法再次单击CAPSLOCK键返回中文输入法

希望能提供改功能选项

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/issues/54
