### ISSUE TITLE
建議翻譯功能支援繁體中文

### ISSUE THREAD

**Issue by WingCH** [dongyuwei/hallelujahIM#69]
建議翻譯功能支援繁體中文
Thanks

**Comment by dongyuwei** [comment]
可以考虑，opencc应该可以自动处理简繁转换。更好的方案是支持配置自定义翻译词典，如英-日翻译词典。

**Comment by dongyuwei** [comment]
不知道实际意义有多大？太小众的话感觉不值得改动。

**Comment by WingCH** [comment]
最近又開始使用這個輸入法！非常好用
分享一個可以簡單做翻譯功能支援繁體中文的方法
1. `/Library/Input Methods/hallelujah.app/Contents/Resources` 找到 `words_with_frequency_and_translation_and_ipa.json`
2. 用其他工具將整份簡體中文轉成繁體中文 (我用的是vscode)
3. 登出後重新登入

題外話
本身打算用opencc, 但xcode  有些神奇error 。。。
