### ISSUE TITLE
@sierra选词好像有问题 Im troubled by choosing words

### ISSUE THREAD

**Issue by xzpjerry** [dongyuwei/hallelujahIM#7]
出来选词框后 用F1-F12下面的数字键选不到词
表现为中断了输入，比如我打进 sug， 第二个是suggestion， 我敲「2」，然后就输成了sug2

**Comment by dongyuwei** [comment]
@xzpjerry 谢谢报告问题---居然一直没有收到github消息提醒。
我今天才更新到Sierra系统，确实有问题。选词问题已经fix了。但是二级翻译列表依然无法展现了（应该是apple input method kit 底层api变化了）。

请下载最新的release： https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.2

**Comment by dongyuwei** [comment]
hi, @xzpjerry 请下载最新版 https://github.com/dongyuwei/hallelujahIM/releases/latest 再试试吧。
