### ISSUE TITLE
建议增加开关可以配置默认不打开单词联想功能，类似默认英文输入法

### ISSUE THREAD

**Issue by goomoon** [dongyuwei/hallelujahIM#70]
现在默认都开启单词联想功能，会导致在部分软件如开机输入密码或 iCloud 输入密码时，都需要手动shift切换，而且在输入iCloud 密码时手动切换无效无法登陆；最终导致还是无法完全替代默认的英文输入法。

建议：增加开关配置可以设置默认是否开启英文单词功能，不开启就跟mac系统默认英文输入法一样；

另外建议：可以考虑增加开启快捷键，方便键盘党

谢谢提供这么好的英文学习软件~

**Comment by dongyuwei** [comment]
hallelujahIM 和系统默认的拉丁/英文输入法有很多差异，输入密码建议使用系统内置的输入法。
