### ISSUE TITLE
建议在密码框中自动禁用

### ISSUE THREAD

**Issue by liyafe1997** [dongyuwei/hallelujahIM#72]
如题，不然经常在打密码时启用，要手动切一下不太方便。

**Comment by dongyuwei** [comment]
输入法没有办法知道当前输入的input source是不是在密码框，这是操作系统决定的。

**Comment by liyafe1997** [comment]
可为什么别的输入法不会在输密码的时候出现呢？

**Comment by dongyuwei** [comment]
osx对于 latin 输入法都允许在密码框中使用，其他语言的输入法不允许。hallelujah 输入法是英文输入法，也是 latin 系的。配置参见： https://github.com/dongyuwei/hallelujahIM/blob/master/Info.plist#L46

**Comment by dongyuwei** [comment]
严格来说，这是个系统安全漏洞。苹果没有限制第三方输入法，这个可能会泄露用户的敏感信息。中文输入法不能输入密码，会自动使用系统内置的英文输入法。

**Comment by liyafe1997** [comment]
明白了，谢谢
