### ISSUE TITLE
输入字母后按esc键的问题

### ISSUE THREAD

**Issue by kunglin** [dongyuwei/hallelujahIM#74]
在某些输入框中，输入字母后按esc单词没有消失，反而留了一个带有下划线的单词在那里，也不能删除，只能重新输入一个字母替换，请问这个问题可以解决么。
在chrome的链接栏，typora里面，网易云音乐搜索框都会出现。是因为这些搜索栏用的不一样的格式么

**Comment by dongyuwei** [comment]
在chrome的地址栏确实有这个问题。Mac 10.15.3 ， Chrome 79.0.3945.130
这种特定 app 相关的 bug 不好处理。按空格键也可以消除。
之前的设计是 esc 时把当前输入的 text 提交了，现在看可能和Mac系统升级到 10.15也有关系。

**Comment by kunglin** [comment]
同事的air上也有这个问题。os High Sierra 10.13.6 ，chrome 79.0.3945.130，应该也能看出不是系统问题了吧？

**Comment by dongyuwei** [comment]
> 之前的设计是 esc 时把当前输入的 text 提交了
这个是指通常情况下。现在测试在其他 app 里面也失效了，不只是 chrome 地址栏有问题。

**Comment by kunglin** [comment]
期待你的修复😀

**Comment by dongyuwei** [comment]
fixed: https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.5.0
请下载安装最新版 hallelujah-20200226202906.pkg

**Comment by dongyuwei** [comment]
code diff: https://github.com/dongyuwei/hallelujahIM/commit/eff88cbbe895f3b274ac3c3c6ff2ecb9a6dbccb2

**Comment by kunglin** [comment]
感谢，已正常.不过我又发现了一个小问题，在聚焦中搜索此软件名后看到的版本号还是1.0.0😂

**Comment by dongyuwei** [comment]
聚焦是指什么？

**Comment by kunglin** [comment]
就是spotlight，command+space 召唤出来的那个搜索框

**Comment by dongyuwei** [comment]
oh, 这个先不管了。这里的 version 确实好久没有更新了，暂时不影响使用。
后面有空可以做发布前自动升级 version。
