### ISSUE TITLE
为什么在word里没法用哈利路亚？

### ISSUE THREAD

**Issue by swy1997** [dongyuwei/hallelujahIM#79]

**Comment by dongyuwei** [comment]
具体什么表现？mac 版本和 word 版本报告一下吧。

**Comment by JELEL777** [comment]
我备忘录和word都开不了 无法选中输入法 点击后会弹回之前默认的

**Comment by dongyuwei** [comment]
> 我备忘录和word都开不了 无法选中输入法 点击后会弹回之前默认的

试过重启系统没？

**Comment by dongyuwei** [comment]
备忘录是指 note.app 吗？我用哈利路亚输入法没有问题。

**Comment by koenzhao** [comment]
Tried with word and note app, the IM works well.
MacOS: 10.15.7
Word: 16.51 (21071101)
Note: 4.7 (1111.23)

**Comment by dongyuwei** [comment]
thanks @koenzhao 
I'll close this issue.
