### ISSUE TITLE
优化快速选词

### ISSUE THREAD

**Issue by bang88** [dongyuwei/hallelujahIM#8]
我有个习惯就是在输入的时候按空格键就确认当前输入的文字，现在安装最新版的方式是需要按Enter键或者手动输入1、2、3、4、5、6、7 直接选词。

能不能有个选项可以设置使用空格键选词然后继续输入。现在按Enter键有点累 😢  

谢谢。

**Comment by dongyuwei** [comment]
你用的是macOS Sierra version 10.12吗？

**Comment by bang88** [comment]
对最新版
-- 
bang

**Comment by bang88** [comment]
10.12.3 (16D32)

**Comment by dongyuwei** [comment]
我看一下。在10.12系统上问题很多。

**Comment by bang88** [comment]
确实有很多问题
-- 
bang

**Comment by dongyuwei** [comment]
hi @bang88 , 试试 https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.1.5 这个版本吧。支持空格提交选中的词。

我不太清楚在使用空格选词时，单词后面自动附加一个空格是不是更好？但在编程环境中这样又不太合适。

**Comment by bang88** [comment]
@dongyuwei 好的 我看下，应该是习惯问题吧哈哈

**Comment by dongyuwei** [comment]
翻译列表的展示位置还有bug；第一次输入较快时也会有恼人的问题。重启hallelujah进程是一个（不得已的）方法 :)

**Comment by bang88** [comment]
还有 我锁定了Mac 登陆的时候不能输入英文字母，要手动切换为英语输入法

**Comment by dongyuwei** [comment]
不太明白这个是啥意思？需要程序做什么改进？

**Comment by bang88** [comment]
我不知道是什么问题，如果当前输入法是hallelujahIM 输入密码的时候什么都输入不了

我刚下载了最新版的输入 发现不能输入了

**Comment by dongyuwei** [comment]
10.12.2 (16C67) 亲测可以空格选词。你的是10.12.3 (16D32)？我最近升级操作系统都不成功，很奇怪的。

**Comment by bang88** [comment]
嗯 我的是3

**Comment by bang88** [comment]
![image](https://cloud.githubusercontent.com/assets/433259/23338276/9fb63610-fc38-11e6-8c1b-d685154a1d0b.png)

**Comment by dongyuwei** [comment]
暂时爱莫能助了，等哪天我系统能升级了再帮你看看吧。

关于输入密码，mac系统上几乎所有app的密码输入框输入时都可以被英文输入法获取到，唯独chrome浏览器有特殊处理，无法监听密码输入。我之前在hallelujah输入法中集成了简单的密码管理器功能，后来砍掉了这个功能。

**Comment by bang88** [comment]
我这里确实还不行。

其他问题：

1. 开发的时候经常需要command + s 保存，现在不行
2. 我习惯 command + m 最小化窗口现在也被输入法拦截了 当成输入

是不是需要忽略这些功能键

**Comment by dongyuwei** [comment]
你先把以前老的输入法卸载掉，进程杀死，再替换文件，再在Input Sources中启用。确保程序是最新的。

**Comment by bang88** [comment]
我删除 Input Methods 下面的app就可以了吗

**Comment by dongyuwei** [comment]
no，
1. delete the hallelujah from Input sources
2. kill the old hallelujah process
3. replace the hallelujah input method app in /Library/Input Methods/.
4. add the hallelujah to Input sources
5. switch to hallelujah, use it.

**Comment by bang88** [comment]
Get.  it works well.

**Comment by dongyuwei** [comment]
ok。谢谢反馈意见。

**Comment by bang88** [comment]
现在还有一个小问题就是 在输入英文的时候 如果输入`'`号 之前的单词会不见了。回退删掉这个‘号就可以

**Comment by dongyuwei** [comment]
确实有这个问题。10.12的兼容性太差了。貌似特殊符号都有这问题，我再看看。

**Comment by bang88** [comment]
嗯好的，你有没有使用`hyper`这个终端，在这个终端里面用不了

**Comment by dongyuwei** [comment]
我用iTerm2.

**Comment by bang88** [comment]
https://hyper.is/

**Comment by bang88** [comment]
应该都是一样才对。。  不过还是很好用了，我用hyper的时候再切回去别的输入法。

**Comment by dongyuwei** [comment]
在hyper里面用不了是什么表现？无法显示候选词？能正常输入英文吗？

**Comment by bang88** [comment]
如果按了shift键，输入字母的时候会丢失字母，输入不了单词

**Comment by bang88** [comment]
你可以装一个试试 很小

**Comment by dongyuwei** [comment]
这个。。我不想为了兼容一个不常用的app而改动通用代码。除非这个改动适用于所有app。

**Comment by bang88** [comment]
嗯 好的。  如果有空的话可以看看哈，我现在没有使用ITerm 这个终端。

**Comment by dongyuwei** [comment]
ITerm 很好用很强大。配合fish，mosh等非常爽，推荐。

**Comment by bang88** [comment]
好的。
我是用 hyper + zsh 哈哈哈。

**Comment by dongyuwei** [comment]
zsh啊，我觉得fish才是神器，哈哈！
好奇你用什么特殊工具来接收github通知的吗？反应好快。

**Comment by bang88** [comment]
有邮件通知
-- 
bang

**Comment by xyoun** [comment]
好像现在默认第一个都是你输入的单词，而不是补全出来的？
![1543478467365](https://user-images.githubusercontent.com/3148266/49207482-fd777d80-f3ef-11e8-85e3-222c1c9803ca.jpg)
