### ISSUE TITLE
翻译窗口在应用全屏的时候会消失

### ISSUE THREAD

**Issue by ltpeach** [dongyuwei/hallelujahIM#81]
halleluja 非常棒！

翻译窗口会偶尔消失。在某一个应用全屏的时候，即使再退回全屏状态，翻译窗口也会一直消失。

重启电脑之后，能用翻译窗口。但是word全屏之后，就不能用了。

希望有助于解决bug。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/releases/tag/v1.5.3 修复了这个 bug。我测试了 Chrome 浏览器和 iterm2 这些 apps。没有word，无法测试。

@ltpeach 谢谢反馈 bug！

**Comment by dongyuwei** [comment]
重启电脑代价太高了，可以在activity monitor 中杀掉hallelujah 进程，操作系统会自动重启输入法进程。

**Comment by ltpeach** [comment]
非常感谢及时修复。现在已经没问题了！ 亲测好用！

**Comment by tedjianlichen** [comment]
Super love hallelujah, Appreciate what you have done bro, thanks a lot.
![bitmoji](https://sdk.bitmoji.com/render/panel/368470ce-a96e-4950-967e-4f527bd6818c-b04ccb62-bb9b-413a-b31c-f327a36ac12d-v1.png?transparent=1&palette=1&width=246)

if you can add the feature 「Automatic capitalize the first letter」will be more competitive.

Thanks

**Comment by dongyuwei** [comment]
@tedjianlichen thanks for your suggestion!
You can hold `shift` while you inputing the words at this time.
