### ISSUE TITLE
怎么卸载呢？

### ISSUE THREAD

**Issue by liewpika** [dongyuwei/hallelujahIM#82]
请问可以提供卸载方式吗？

**Comment by dongyuwei** [comment]
删除 /Library/Input\ Methods/hallelujah.app 就行了。删除之前在输入法中卸载一下，或者先手动杀掉输入法进程。

**Comment by dongyuwei** [comment]
这种问题可以Google一下。

**Comment by liewpika** [comment]
感觉不太习惯，安装以后，原来的按中/英 键位可以切换中英文输入的方式，只能定向从中文切到Hallelujah，无法从Hallelujah切回中文，仅可通过control+ space 的形式切换，希望可以考虑增加这个偏好设置

**Comment by dongyuwei** [comment]
参考 https://github.com/dongyuwei/hallelujahIM/issues/54
暂无fix计划。
