### ISSUE TITLE
开发者能适应到win平台吗

### ISSUE THREAD

**Issue by xylewis** [dongyuwei/hallelujahIM#83]
我们翘首以盼

**Comment by dongyuwei** [comment]
曾经试图移植到 windows 平台。没有 windows 机器，在虚拟机里编程体验比较差，暂时没有时间和精力投入。

**Comment by allinu** [comment]
+1

**Comment by flytigerzhang** [comment]
+1

**Comment by dongyuwei** [comment]
公司项目已经压力很大了，暂无win版开发计划。商业合作可以联系我

**Comment by sunday123** [comment]
Windows版本感觉很有必要,Windows占有很大一批用户

**Comment by dongyuwei** [comment]
windows开发体验太差了，可能跟我使用虚拟机性能不行有关。折腾过pime。

**Comment by sunday123** [comment]
> windows开发体验太差了，可能跟我使用虚拟机性能不行有关。折腾过pime。

开发体验感觉和习惯有关,我苹果电脑 Windows几乎每天用,个人感觉mac用着确实舒适些
目前苹果的输入法也有安卓版本，谷歌的gboard也有ipa版本
总的来说，用户最重要，Windows用户规模也是最大的

目测 window10专业版自带英文输入法 局限于在微软的软件（比如自带的记事本）才有候选词（Windows里面称为联想）
还有Google input浏览器插件 英文也有候选词，局限于浏览器里面使用
