### ISSUE TITLE
MS word 中输入法有时会失效。

### ISSUE THREAD

**Issue by Atlantis-Luna** [dongyuwei/hallelujahIM#84]
触发条件：开启MAC输入法设置中的“自动切换到文稿的输入法”，在word 中切换到hallelujahIM 输入法以后，切换窗口到其他运用程序，用其他输入法输入以后（例如系统自带的拼音输入法），然后再切换回word，有时会导致输入法无法正常工作。

希望能解决下这个bug，谢谢。

**Comment by dongyuwei** [comment]
输入法无法正常工作的具体表现是什么，没有候选词和翻译功能了？

**Comment by Atlantis-Luna** [comment]
是的，就和把输入切换成英文一样，直接输入到word中。

**Comment by dongyuwei** [comment]
> 触发条件：开启MAC输入法设置中的“自动切换到文稿的输入法”

不开启这个，可以正常使用吗？

**Comment by Atlantis-Luna** [comment]
不清楚，没有试过，我一般都是勾着这个选项的。

**Comment by Atlantis-Luna** [comment]
> > 触发条件：开启MAC输入法设置中的“自动切换到文稿的输入法”
> 
> 不开启这个，可以正常使用吗？

目前发现，好像和这个没有关系，我一直在word 界面也出现了同样的情况，具体还没有办法确定是什么原因造成的，有没有日志信息可以查看？

**Comment by dongyuwei** [comment]
日志可以打开 Console.app，在里面搜索hallelujah。日志估计不会有什么帮助，这种特定 app 的兼容问题只能 debug 看看。

**Comment by Atlantis-Luna** [comment]
> 日志可以打开 Console.app，在里面搜索hallelujah。日志估计不会有什么帮助，这种特定 app 的兼容问题只能 debug 看看。

确实，只能看到这个。

register name: com.apple.inputmethodkit.abnormaldeath object: github.dongyuwei.inputmethod.hallelujahInputMethod token: f439d pid: 56688

**Comment by Atlantis-Luna** [comment]
发现问题了，不是输入法的问题，是我自己在使用过程中不小心按到了“shift” 键。

顺带提两个建议：
1.  通过“shift”切换的时候能否增加的状态显示。
2. 能否匹配下苹果那个通过“caps lock”键切换输入法的功能。

**Comment by dongyuwei** [comment]
1可以考虑增强一下，可能换个快捷键。
2暂时没有打算做
