### ISSUE TITLE
Is it possible to use with different language?

### ISSUE THREAD

**Issue by drsnn** [dongyuwei/hallelujahIM#85]
Hi 

Thanks for this application. is it possible to add other languages ( for example gemany, french  or swedish ). Sometimes   we use different languages.

Thanks

**Comment by dongyuwei** [comment]
Hi @drsnn,
Yes it's possible if you have the proper dictionary, eg:  gemany-english dictionary, then hallelujah can display the translation in gemany.

**Comment by drsnn** [comment]
Thanks for  Dongyuwei

Is there any guides which helps to me for installation. Thank you very much.

**Comment by dongyuwei** [comment]
Hi @drsnn 
Currently you need to modify the `translation` in 
https://github.com/dongyuwei/hallelujahIM/blob/master/dictionary/words_with_frequency_and_translation_and_ipa.json, replace the Chinese translation with your translation. Then compile the app in Xcode manually. 

Sorry There should be a better way to automatically handle the replacement. Need some time to do it.

**Comment by drsnn** [comment]
Thank you very Much for this good work. Thanks
