### ISSUE TITLE
[bug] 某些场景下输入会出现一个矩形框

### ISSUE THREAD

**Issue by Ti800** [dongyuwei/hallelujahIM#91]
系统：Macos 10.15.6

复现步骤：
<img width="647" alt="截屏2020-07-18 下午12 04 13" src="https://user-images.githubusercontent.com/53323379/87844357-eea84c00-c8ee-11ea-9847-b56190dc2753.png">

**Comment by Ti800** [comment]
是否需要更多信息？这个bug太恼人了，很多调用类似输入框的应用下都会出现。

**Comment by dongyuwei** [comment]
除了密码框，其他文本框也有这种问题吗？操作系统什么版本，具体出问题的 app 都有哪些？输入法本身使用的是否是最新版？信息越多越有利于解决问题。

**Comment by Ti800** [comment]
1.暂时只发现密码框
2.系统：macOS 10.15.6
3.输入法版本为v1.5.3(fix issues/81)
4.类似的密码框调用bug均能复现，例如邮件.app
![image](https://user-images.githubusercontent.com/53323379/89247376-c84d1500-d63f-11ea-904f-f27a240cce37.png)

系统设置
![image](https://user-images.githubusercontent.com/53323379/89247784-a902b780-d640-11ea-9f96-e9d6d54f4b3d.png)
![image](https://user-images.githubusercontent.com/53323379/89247812-b9b32d80-d640-11ea-832f-9877df873e49.png)

**Comment by dongyuwei** [comment]
密码框比较特殊，建议切换到系统英文输入法输入密码。

**Comment by Ti800** [comment]
又尝试了rime，无此现象发生。
或者是否可能在遇到密码框的时候自动切换到系统英文输入法？

**Comment by dongyuwei** [comment]
不太清楚 Rime怎么做的，可以研究一下。我之前探索过，输入法可以知道当前输入的 app 是哪个，但是很难知道具体的文本框类型是什么。

**Comment by dongyuwei** [comment]
https://stackoverflow.com/questions/6569183/in-cocoa-how-to-check-a-textfield-is-for-password

Rime是中文输入法，hallelujah 是 latin 输入法，所以不太一样。一种办法是将hallelujah声明为`zh-Hant`，也许可以绕开这个问题，但不知道有没有其他副作用。
