### ISSUE TITLE
Caps key can not switch between hallelujahIM and other IM

### ISSUE THREAD

**Issue by lazywalker** [dongyuwei/hallelujahIM#93]
macOS 10.15 use caps key to switch between IMs,  by default,  this feature can be enable by check the checkbox `Use Caps key to switch ...`, long press to enable uppercase locked. 

hallelujahIM does not follow this feature, even the checkbox has been checked. 
that might be a bug,  i think.

**Comment by dongyuwei** [comment]
duplicated with https://github.com/dongyuwei/hallelujahIM/issues/97
