### ISSUE TITLE
Caps Lock切换输入法的问题

### ISSUE THREAD

**Issue by MLZC** [dongyuwei/hallelujahIM#97]
![image](https://user-images.githubusercontent.com/18593673/103341041-c96f5a80-4a96-11eb-93f4-605517a5d67c.png)

按照上图描述，原生输入法之间可以通过点按caps lock来切换， 长按caps lock进入大写模式。但是在哈利路亚输入法中，无法通过caps lock切换到上一个输入源。 无论是点按还是长按caps lock，都是进入大写模式。

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/hallelujahIM/issues/54
