### ISSUE TITLE
希望有win10版本

### ISSUE THREAD

**Issue by Pantyhose-X** [dongyuwei/hallelujahIM#99]
你可以开发一个 监听输入法工具，应用于学习语言，这样可以纠正发音和加深记忆，调用文本转语音TTS 朗读输入单词或句子。 `输入空格` 后TTS朗读单词，`输入空格`10秒后朗读句子。
你可以内置 [mozilla文字转语音](https://github.com/mozilla/TTS) [coqui-ai TTS](https://github.com/coqui-ai/TTS)或调用Win10内置的或调用Win10安装的

[YouTube演示](https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213)

不以英语为母语的人都需要学习英语，市场非常广

**Comment by dongyuwei** [comment]
mac自带有一个命令say，可以读单词。

**Comment by Pantyhose-X** [comment]
> mac自带有一个命令say，可以读单词。

您可以基于[NVDA]（https://github.com/nvaccess/nvda）
*关闭屏幕阅读器关闭所有其他语音提示。
*独立使用键盘阅读器

**Comment by dongyuwei** [comment]
暂无windows版开发计划，谢谢关注！

**Comment by dongyuwei** [comment]
https://github.com/dongyuwei/PIME/tree/master/python/input_methods/hallelujah 本输入法已经移植到Windows平台。
